### PR TITLE
Launch command

### PR DESCRIPTION
**Pull request by Daft-Freak**
Adds a `LNCH` command which allows ~the device to serve lunch~ launching flies in the same way that the launcher does. Also sends back an OK at the end of flash/save.

This is working towards making auto-launch optional and work for files too. (Need to do some tool bits...)

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Patched a LNCH command into the tools to test this, seems to work fine! Worth adding the ability to launch from a block/offset, for completeness? Though I don't know how the tool would even handle that.

```diff
diff --git a/src/ttblit/core/blitserial.py b/src/ttblit/core/blitserial.py
index cb4ff2c..6e4c694 100644
--- a/src/ttblit/core/blitserial.py
+++ b/src/ttblit/core/blitserial.py
@@ -120,6 +120,12 @@ class BlitSerial(serial.Serial):
                 sent_byte_count += chunk_size
                 progress.update(chunk_size)
 
+    @firmware_command
+    def launch(self, file_path):
+        command = f'32BLLNCH{file_path}\x00'
+        self.reset_output_buffer()
+        self.write(command.encode('ascii'))
+
     @firmware_command
     def erase(self, offset):
         self.write(b'32BLERSE\x00')
diff --git a/src/ttblit/tool/flasher.py b/src/ttblit/tool/flasher.py
index 444f1cf..1e46e5e 100644
--- a/src/ttblit/tool/flasher.py
+++ b/src/ttblit/tool/flasher.py
@@ -21,7 +21,7 @@ def serial_command(fn):
     @click.option('ports', '--port', multiple=True, help='Serial port')
     @functools.wraps(fn)
     def _decorated(ports, **kwargs):
-        if not ports:
+        if not ports or ports[0].lower() == 'auto':
             ports = BlitSerial.find_comport()
 
         for port in ports:
@@ -31,6 +31,26 @@ def serial_command(fn):
     return _decorated
 
 
+@flash_cli.command()
+@serial_command
+@click.argument('file_path', type=pathlib.Path, required=True)
+def launch(blitserial, file_path):
+    blitserial.launch(file_path)
+
+
+@flash_cli.command()
+@serial_command
+@click.argument('file', type=pathlib.Path, required=True)
+@click.argument('directory', type=str, default='sd:/')
+def install(blitserial, file, directory):
+    blitserial.reset_to_firmware()
+    if directory.startswith('flash:'):
+        blitserial.send_file(file, 'flash')
+    else:
+        directory = directory.replace('sd:', '')
+        blitserial.send_file(file, 'sd', directory=directory)
+
+
 @flash_cli.command()
 @serial_command
 @click.option('--file', type=pathlib.Path, required=True, help='File to save')
 ```

**Comment by Daft-Freak** [comment]
It uses the same function as the `launch` API, so `flash:/[block]` should work.

I was thinking of something like this at the end of sending a file:
```py
        response = serial.read(8)

        if response == b'32BL__OK':
            # get block for flash
            if dest == 'flash':
                block, = struct.unpack('<H', serial.read(2))
                print(block)

            # do launch if requested
```

to replace the current always auto-launching on flash. (`--launch` option to flash/save maybe?)



(Hmm, that line about "auto" in your diff makes me think that `--port all` is gone in the refactor, though it's been a while since I last used that...)

**Comment by Gadgetoid** [comment]
Yes I think `--port all` has gone. BlitSerial `find_comport` - called by default when no port is specified - seems to return *all* matching devices though:

```python
    @classmethod
    def find_comport(cls):
        ret = []
        for comport in serial.tools.list_ports.comports():
            if comport.vid == 0x0483 and comport.pid == 0x5740:
                logging.info(f'Found 32Blit on {comport.device}')
                ret.append(comport.device)

        if ret:
            return ret

        raise RuntimeError('Unable to find 32Blit')
    ```

Which would suggest `all`  is implicit since anything wrapped in the `serial_command` decorator runs for every port in the list.

**Comment by Daft-Freak** [comment]
I don't imagine there are going to be that many people having multiple blits plugged in anyway... and we're getting off topic again :smile:

**Comment by Gadgetoid** [comment]
Forgot to merge this :eyes: 

Thank you!

**Pull request merged**
