### PR TITLE
SD Card fixes

### PR DESCRIPTION
**Pull request by Daft-Freak**
Split out the SD card fixes from #204 as it would be a good idea to merge these first.

### CODE REVIEW

**Comment by Daft-Freak** [comment]
Oh, the #pragma fix ended up in here too...

**Comment by Gadgetoid** [comment]
Ah, reverting all of my "improvements" to fatfs_sd :D Thank you!

I'll check this out when I can and make sure things still work as expected. Might be interesting to see if this happens to fix any of the numerous other SD card woes that have befallen us, too.

**Comment by Daft-Freak** [comment]
#204 should rebase nicely on top of this. (Okay, it will... I've already done it in an attempt to get my SD working: https://github.com/Daft-Freak/32blit-beta/tree/MassStoragePR)

**Comment by Daft-Freak** [comment]
Seems the revert is causing issues in music-player.

**Comment by Daft-Freak** [comment]
Attempt to get both music-player and storage to work at the same time resulted in:
```diff
diff --git a/32blit-stm32/Src/fatfs_sd.c b/32blit-stm32/Src/fatfs_sd.c
index eebbf83..a6b8571 100644
--- a/32blit-stm32/Src/fatfs_sd.c
+++ b/32blit-stm32/Src/fatfs_sd.c
@@ -146,9 +146,21 @@ static bool SD_RxDataBlock(BYTE *buff, UINT len)
 	if(token != 0xFE) return FALSE;
 
 	/* receive data */
-	do {
-		SPI_RxBytePtr(buff++);
-	} while(len--);
+	if(len > 16)
+	{
+		// SD card expects 0xff dummy bytes for reads
+		for(unsigned int x = 0; x < len; x++){
+			buff[x] = 0xff;
+		}
+
+		HAL_SPI_TransmitReceive(HSPI_SDCARD, buff, buff, len, SPI_TIMEOUT);
+	}
+	else
+	{
+		do {
+			SPI_RxBytePtr(buff++);
+		} while(len--);
+	}
 
 	/* discard CRC */
 	SPI_RxByte();

```

(Or half-reverting the revert, but only for big transfers)

**Comment by Daft-Freak** [comment]
Okay, the latest fix from #204 fixes music-player as well. (Pulled in here as well.)

**Comment by Gadgetoid** [comment]
Thank you- sorry I was confused about the nature of these fixes (it's been a busy few weeks both at work and home (more work, haha) and my brain is tied in knots). Thank you!

**Pull request merged**
