### PR TITLE
Misc BMP/screenshot/surface fixes

### PR DESCRIPTION
**Pull request by Daft-Freak**
Mostly discovered by all the random junk on my SD... First two are the most important, the other two just expand BMP support a little.

Not fixed:
- Having an image that doesn't fit in the static buffer on your SD card explodes.
- Paletted BMPs can't have alpha, which is not really a problem for screenshots, but the "alpha" field is written as 0 from most editors...

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Ooh thank you!

Ooof regarding 0 alpha- basically initialising your image with a trash palette because you can’t tell if it’s *really* supposed to be 0 or just 0’d by an editor that’s only dealing with RGB?

Could *possibly* add an out for images that don’t fit in the buffer. Anything much larger is probably going to break anyway. Surface::load(string, buf) would need a Surface::load(string, buf, size) perhaps, and baulk with nullptr if w*h*d exceeds the given buffer size. Bit like “snprintf”?

**Comment by Daft-Freak** [comment]
I think the alpha field is defined as "must be zero". I suppose since we already have to loop through the palette to swap R/B, we could check if every entry is 0 and set them to 255...

Also passing the size of the buffer is probably a good idea, most of the time you're passing in a static buffer so it would just be `load(..., buffer, sizeof(buffer))`... or just default it to 0.

**Comment by Gadgetoid** [comment]
Fixes or... in the case of my code... horrible breaks:

```diff
diff --git a/32blit/graphics/surface.hpp b/32blit/graphics/surface.hpp
index 5ff0da1..96eda0d 100644
--- a/32blit/graphics/surface.hpp
+++ b/32blit/graphics/surface.hpp
@@ -124,7 +124,7 @@ namespace blit {
 
     static Surface *load(const packed_image *image, uint8_t *data, size_t data_size);
     static Surface *load(const packed_image *image) {return load(image, nullptr, 0);};
-    static Surface *load(const uint8_t *image, uint8_t *data, size_t data_size) {return load((packed_image *)image, nullptr, 0);};
+    static Surface *load(const uint8_t *image, uint8_t *data, size_t data_size) {return load((packed_image *)image, data, data_size);};
     static Surface *load(const uint8_t *image) {return load((packed_image *)image, nullptr, 0);};
 
     static Surface *load_read_only(const packed_image *image);
 ```

I can probably just apply this as I merge.

**Comment by Daft-Freak** [comment]
Nope, I don't see a mistake there :wink:

**Comment by Gadgetoid** [comment]
This will serve us right for not just removing one of those overloads altogether.

**Comment by Gadgetoid** [comment]
Thank you!

**Pull request merged**
