### PR TITLE
Clearing probes fixes.

### PR DESCRIPTION
**Pull request by AndrewCapon**
Added clear_all_probes() to reset all probes to init state.

Some fixes to actually clear the probes correctly.

### CODE REVIEW

**Comment by Daft-Freak** [comment]
Not entirely related to this PR, but clang-tidy wants the shiny new for loops:

`for(ProfilerProbesIter iP = m_probes.begin(); iP != m_probes.end(); iP++)` -> 
`for(auto probe : m_probes)`

(It's one of the warnings I haven't got around to fixing yet.)

**Comment by AndrewCapon** [comment]
Does it always complain about iterator loops or only the case where you iterate through all?

**Comment by Daft-Freak** [comment]
For a range, it usually suggests using `auto` instead of the iterator type. You can check the warnings in the output for the Travis Linux build: https://travis-ci.com/github/pimoroni/32blit-beta/jobs/298290759

**Comment by AndrewCapon** [comment]
Sorry, I can't bring myself to use "auto"!

**Comment by AndrewCapon** [comment]
How do you get the clang-tidy stuff when building locally?

**Comment by Daft-Freak** [comment]
Assuming a `clang-tidy` in PATH somewhere
```
cmake "-DCMAKE_CXX_CLANG_TIDY=clang-tidy;-header-filter=32blit;-checks=performance-*,portability-*,modernize-*,-modernize-use-trailing-return-type,-modernize-avoid-c-arrays,-modernize-use-nodiscard" [other opts]
```
(What Travis is doing) or

```json
    "cmake.configureSettings": {
        "CMAKE_CXX_CLANG_TIDY": ["clang-tidy", "-header-filter=32blit", "-checks=performance-*,portability-*,modernize-*,-modernize-use-trailing-return-type,-modernize-avoid-c-arrays,-modernize-use-nodiscard"]
    },
```
With VS Code/CMake tools. There are a few defaults disabled due to being incredibly noisy. (And I don't think `auto f() -> int;` is an improvement on `int f();`...)

It will fail to build if you use it on an STM32 build though (it dies on the few `.c` files that actually contain C++)

**Comment by AndrewCapon** [comment]
Thanks, I will start running everything through this to tidy up before committing.

**Pull request merged**
