### PR TITLE
Adds LICENSE and README to dist for #376

### PR DESCRIPTION
**Pull request by Gadgetoid**
Could probably stand to have some basic docs here, but some stuff might necessarily be platform dependent, ie:

1. instructions for installing games/flashing firmward in blit release
2. instructions for joining/hosting multiplayer (2 player) in SDL releases
3. ???

### CODE REVIEW

**Comment by Daft-Freak** [comment]
Won't that include those files in every user's game as well? (Since 32blit.cmake is included there too). Also `DESTINATION .` is probably more appropriate (or just not `bin`...)

**Comment by Gadgetoid** [comment]
Weirdly pushing into `bin` seemed to work, all files in the zip are in the base directory which is handy. I guess that's because CPack is eating the subdir? I'm not sure!

Good point re this ending up in ALL THE THINGS. Drat. It's a GOOD THING:tm: that the license does that, but the README really isn't generic enough.

**Comment by Gadgetoid** [comment]
Oh actually it extracts to a `bin` folder, I was just being dumb.

**Comment by Gadgetoid** [comment]
night time mergin' oooh yeah
night time mergin' give ya a scare
night time mergin' don't you dare
night time mergin' don't even care

**Pull request merged**
