### PR TITLE
path change

### PR DESCRIPTION
**Pull request by mylogon341**
make flash-loader creates path so either we need to cd into it or prefix the path with the directory

### CODE REVIEW

**Comment by Gadgetoid** [comment]
This is a step in the right direction- thanks! 

I think this relates to #122 in that we have some confusion about where a build should be triggered from. I may have spread my (not necessarily bad) habit of compiling from individual example directories via the documentation.

I'm told it's better to compile from the root, since it shares the HAL (32blit-stm32) and API (32blit) across all builds.

**Comment by Gadgetoid** [comment]
Okay I'm doing some significant re-writing of the docs off the back of this. Stay tuned!

**Comment by mylogon341** [comment]
Happy to help out :)

**Comment by Gadgetoid** [comment]
I've started reshuffling some of the 32Blit documentation to hopefully isolate the different stages and make them clearer: https://github.com/pimoroni/32blit-beta/commit/f5ef27c75a3ca5d8dc45f7720fe926d0699d394c

Your input on these changes would be greatly appreciated!

**Pull request closed without merging**
