### PR TITLE
Font fix

### PR DESCRIPTION
**Pull request by ahnlak**
Centres narrow letters when rendering as a fixed font; otherwise these are left-aligned and the kerning is horrible.

### CODE REVIEW

**Comment by Daft-Freak** [comment]
I'd move the `- fixwidth` down to the `c.x += char_width;`, then you could move setting `char_width` above the loops and fix the x loop issue you also pointed out.


Oh, and your `{` should be on the line above...

**Comment by ahnlak** [comment]
Hmm, good point on moving the `char_width` setting; I did fiddle with the x loop issue but wasn't entirely convinced the savings were measurable (you have to knock one off the variable width, so that's an extra op per letter to save time on *some* of them...)

Now, if I update this branch do I have to resend the PR or does it all just work itself out?

**Comment by Daft-Freak** [comment]
Ah, right `char_w_variable` can be greater than `char_w` because padding... Maybe just leave that alone then...

Updating the branch should just work.

**Comment by Gadgetoid** [comment]
Thank you!

Definitely an improvement, although it's still a little janky. Occupational hazard if you need fixed-width, I guess!

Before:

image

After:

image

**Pull request merged**
