### PR TITLE
DMA2d interrupt control

### PR DESCRIPTION
**Pull request by zenodante**
Now using interrupt to update DMA2d statement. So we don't need to wait DMA2d to finish its job. State check was added in do_render function to check the update state before rewrite the framebuff and start flip.

### CODE REVIEW

**Comment by zenodante** [comment]
again, I tested it on stm32h750b DK board, havn't got my 32blit hardware yet. So please help to check if it works fine on real hardware :)

**Comment by Gadgetoid** [comment]
Oooh this is super exciting! Will test right away. Thank you.

**Comment by Daft-Freak** [comment]
I think this would be a good use for a squash-merge :smile: ...and since this file is still mostly magic to me, the only comment I have is that some of the function/variable names aren't fully `snake_case`. (Ignoring the IRQHandler, since that has to be like that)

**Comment by zenodante** [comment]
I could fix the name issue after you tested everything is fine:)

**Comment by Gadgetoid** [comment]
@Daft-Freak 

From what I understand this is a state machine along the lines of my interrupt-driven i2c state machine, that uses the DMA2d finished interrupt to trigger the next step in the multi-step DMA2d lores flip. The hires isn't overly affected by this since it's just one step that ties up the DMA2d hardware and back-buffer for a constant amount of time each.

In both cases it - however - this change brings the blocking aspects of the flip routines much higher in the hierarchy and combines the multiple steps of the lores flip into one-long-block (although only the first step in lores actually blocks the back-buffer). Waiting on the back-buffer to be writeable, and then waiting for the DMA2d hardware to be available happens in two loops here:

```c++
static void do_render() {
  if(display::needs_render) {
    while (display::is_frameBuff_occupied()){
      //if framebuff still occupied by last dma2d flip
    }
    blit::render(blit::now());
    while (display::is_dma2d_occupied()){
      //if framebuff still occupied by last dma2d flip
    }
    display::enable_vblank_interrupt();
  }
}
```

`is_frameBuff_occupied` is a check against whether DMA2d is still actively coping something from the back-buffer, in which case the user cannot draw to the display.

And `is_dma2d_occupied` is a check against whether the DMA2d hardware is still performing crucial steps, specifically for the multi-step process of a lores, pixel-doubled flip, in which case another flip cannot begin.

Since both of these are still blocking, we get an earlier hit to `blit::render`, in the case of lores, but the total time occupied by a flip - and subsequently the total time `do_render` will block for remains approximately the same.

@zenodante 

In order to try and "fit" system tasks in the time occupied by the DMA transfers, could `do_render` now become something like:

```diff
diff --git a/32blit-stm32/Src/32blit.cpp b/32blit-stm32/Src/32blit.cpp
index 440afbc..4bad321 100644
--- a/32blit-stm32/Src/32blit.cpp
+++ b/32blit-stm32/Src/32blit.cpp
@@ -181,9 +181,19 @@ void blit_tick() {
     blit_menu();
   }
 
-  do_render();
+  //do_render();^M
+^M
+  if(display::needs_render) {^M
+    while (display::is_frameBuff_occupied()) {^M
+    }^M
+    blit::render(blit::now());^M
+    while(display::is_dma2d_occupied()) {^M
+      blit_i2c_tick();^M
+    }^M
+    display::enable_vblank_interrupt();^M
+  }^M
 
-  blit_i2c_tick();
+  //blit_i2c_tick();^M
   blit_process_input();
   blit_update_led();
   blit_update_vibration();
```

Also I think there are some commented out code sections that can be thrown away, plus some issues with indentation/spacing though I don't mind making a subsequent PR myself to tidy those up.

**Comment by zenodante** [comment]
> @Daft-Freak
> 
> From what I understand this is a state machine along the lines of my interrupt-driven i2c state machine, that uses the DMA2d finished interrupt to trigger the next step in the multi-step DMA2d lores flip. The hires isn't overly affected by this since it's just one step that ties up the DMA2d hardware and back-buffer for a constant amount of time each.
> 
> In both cases it - however - this change brings the blocking aspects of the flip routines much higher in the hierarchy and combines the multiple steps of the lores flip into one-long-block (although only the first step in lores actually blocks the back-buffer). Waiting on the back-buffer to be writeable, and then waiting for the DMA2d hardware to be available happens in two loops here:
> 
> ```c++
> static void do_render() {
>   if(display::needs_render) {
>     while (display::is_frameBuff_occupied()){
>       //if framebuff still occupied by last dma2d flip
>     }
>     blit::render(blit::now());
>     while (display::is_dma2d_occupied()){
>       //if framebuff still occupied by last dma2d flip
>     }
>     display::enable_vblank_interrupt();
>   }
> }
> ```
> 
> `is_frameBuff_occupied` is a check against whether DMA2d is still actively coping something from the back-buffer, in which case the user cannot draw to the display.
> 
> And `is_dma2d_occupied` is a check against whether the DMA2d hardware is still performing crucial steps, specifically for the multi-step process of a lores, pixel-doubled flip, in which case another flip cannot begin.
> 
> Since both of these are still blocking, we get an earlier hit to `blit::render`, in the case of lores, but the total time occupied by a flip - and subsequently the total time `do_render` will block for remains approximately the same.
> 
> @zenodante
> 
> In order to try and "fit" system tasks in the time occupied by the DMA transfers, could `do_render` now become something like:
> 
> ```diff
> diff --git a/32blit-stm32/Src/32blit.cpp b/32blit-stm32/Src/32blit.cpp
> index 440afbc..4bad321 100644
> --- a/32blit-stm32/Src/32blit.cpp
> +++ b/32blit-stm32/Src/32blit.cpp
> @@ -181,9 +181,19 @@ void blit_tick() {
>      blit_menu();
>    }
>  
> -  do_render();
> +  //do_render();^M
> +^M
> +  if(display::needs_render) {^M
> +    while (display::is_frameBuff_occupied()) {^M
> +    }^M
> +    blit::render(blit::now());^M
> +    while(display::is_dma2d_occupied()) {^M
> +      blit_i2c_tick();^M
> +    }^M
> +    display::enable_vblank_interrupt();^M
> +  }^M
>  
> -  blit_i2c_tick();
> +  //blit_i2c_tick();^M
>    blit_process_input();
>    blit_update_led();
>    blit_update_vibration();
> ```
> 
> Also I think there are some commented out code sections that can be thrown away, plus some issues with indentation/spacing though I don't mind making a subsequent PR myself to tidy those up.
> 
> Edit: In all my tinkering with this, I forgot to mention that it's actually working really nicely. Thank you!
Here the is_dma2d_occupied() in following code:
while (display::is_dma2d_occupied()){
      //if framebuff still occupied by last dma2d flip
    }
    display::enable_vblank_interrupt();
The waiting in the while loop is almost impossible to happened because usually the rander function will take more time than DMA2D to finish all its work in lores flip task. Here put the test while loop is to prevent those very light weight render function to run too fast. So put i2c update inside it would cause some problem then.(almost no chance to run~)

Of cause carefully counting the frame rate and average frame generation time in different combinations would be very necessary to judge which one would be better for most situations. 
So we may use mine solution at this moment, then after I received my 32blit, I could do some test in real hardware to get the cpu time counting result to improve it again.

**Comment by Gadgetoid** [comment]
I keep painting myself into a corner trying to encapsulate all of the logic here into the `display` class so that from the perspective of the blit main loop all it needs to do is call `display::update()` and basically everything else happens in the state machine.

Since we can't call `render()` in an interrupt, and since enabling the VBlank interrupt *in* an interrupt didn't seem to go well, I was trying to move the entire state machine out of the interrupt handler and into `display::update()`, which would then be pumped by the main loop.

The interrupt handlers would then just adjust the "state" of the display state machine, an enum looking something like:

```c++
  enum State {
    IDLE,
    FLIP,
    RENDER,
    HIRES_COPY,
    LORES_STEP1,
    LORES_STEP2,
    LORES_STEP3,
    LORES_STEP4
  };
```

I don't know if this is a sensible approach, but it's clear the encapsulation between "display" and "everything else" is getting hazy, and it would be nice if everything were encapsulated cleanly.

**Comment by zenodante** [comment]
> I keep painting myself into a corner trying to encapsulate all of the logic here into the `display` class so that from the perspective of the blit main loop all it needs to do is call `display::update()` and basically everything else happens in the state machine.
> 
> Since we can't call `render()` in an interrupt, and since enabling the VBlank interrupt _in_ an interrupt didn't seem to go well, I was trying to move the entire state machine out of the interrupt handler and into `display::update()`, which would then be pumped by the main loop.
> 
> The interrupt handlers would then just adjust the "state" of the display state machine, an enum looking something like:
> 
> ```c++
>   enum State {
>     IDLE,
>     FLIP,
>     RENDER,
>     HIRES_COPY,
>     LORES_STEP1,
>     LORES_STEP2,
>     LORES_STEP3,
>     LORES_STEP4
>   };
> ```
> 
> I don't know if this is a sensible approach, but it's clear the encapsulation between "display" and "everything else" is getting hazy, and it would be nice if everything were encapsulated cleanly.

WOW
The state machine involve two interrupt and main loop would be quite challenged to keep efficiency and clearance!

**Comment by Gadgetoid** [comment]
I'll have to trust your judgment here, because I have no idea what I'm doing! :laughing:

**Comment by Gadgetoid** [comment]
Much less ambitious set of changes which I can apply after merge if they're okay:

```patch
diff --git a/32blit-stm32/Inc/display.hpp b/32blit-stm32/Inc/display.hpp
index bb9b4dc..1fde7b9 100644
--- a/32blit-stm32/Inc/display.hpp
+++ b/32blit-stm32/Inc/display.hpp
@@ -19,6 +19,13 @@ namespace display {
   extern ScreenMode mode;
   extern bool needs_render;
 
+  enum State {
+    DMA2D_FINISH,
+    DMA2D_LORES_STEP_2,
+    DMA2D_LORES_STEP_3,
+    DMA2D_LORES_STEP_4
+  };
+
   void init();  
 
   void enable_vblank_interrupt(); 
@@ -30,15 +37,15 @@ namespace display {
   void screen_init();
   void ltdc_init();
 	
-	bool is_dma2d_occupied(void);
-	bool is_frameBuff_occupied(void);
-	uint32_t get_dma2d_count(void);
-	void set_dma2d_state(bool occupied);
-	void set_frameBuff_state(bool occupied);
+	bool is_dma2d_busy(void);
+	bool is_framebuffer_busy(void);
+	State get_dma2d_state(void);
+	void set_dma2d_busy(bool busy);
+	void set_framebuffer_busy(bool busy);
   
-  void dma2d_lores_flip_Step2(void);
-  void dma2d_lores_flip_Step3(void);
-  void dma2d_lores_flip_Step4(void);
+  void dma2d_lores_flip_step2(void);
+  void dma2d_lores_flip_step3(void);
+  void dma2d_lores_flip_step4(void);
 }
 
 
diff --git a/32blit-stm32/Src/32blit.cpp b/32blit-stm32/Src/32blit.cpp
index 440afbc..8bba263 100644
--- a/32blit-stm32/Src/32blit.cpp
+++ b/32blit-stm32/Src/32blit.cpp
@@ -154,11 +154,11 @@ const char *battery_charge_status() {
 
 static void do_render() {
   if(display::needs_render) {
-    while (display::is_frameBuff_occupied()){
+    while (display::is_framebuffer_busy()){
       //if framebuff still occupied by last dma2d flip
     }
     blit::render(blit::now());
-    while (display::is_dma2d_occupied()){
+    while (display::is_dma2d_busy()){
       //if framebuff still occupied by last dma2d flip
     }
     display::enable_vblank_interrupt();
diff --git a/32blit-stm32/Src/display.cpp b/32blit-stm32/Src/display.cpp
index b36d77f..0e5434c 100644
--- a/32blit-stm32/Src/display.cpp
+++ b/32blit-stm32/Src/display.cpp
@@ -30,23 +30,23 @@ void DMA2D_IRQHandler(void){
   //clear the flag
 	
   DMA2D->IFCR = (uint32_t)(0x1F);
-	uint32_t count = display::get_dma2d_count();
-	switch(count){
-		case 3:
-			display::set_frameBuff_state(false);
-			display::dma2d_lores_flip_Step2();
+	display::State state = display::get_dma2d_state();
+	switch(state){
+		case display::State::DMA2D_LORES_STEP_2:
+			display::set_framebuffer_busy(false);
+			display::dma2d_lores_flip_step2();
 			break;
-		case 2:
-			display::dma2d_lores_flip_Step3();
+		case display::State::DMA2D_LORES_STEP_3:
+			display::dma2d_lores_flip_step3();
 			break;
-		case 1:
-			display::dma2d_lores_flip_Step4();
+		case display::State::DMA2D_LORES_STEP_4:
+			display::dma2d_lores_flip_step4();
 			break;
-		case 0:   //highres, pal mode goto case 0 directly
+		case display::State::DMA2D_FINISH:   //highres, pal mode goto case 0 directly
 			CLEAR_BIT(DMA2D->CR, DMA2D_CR_TCIE|DMA2D_CR_TEIE|DMA2D_CR_CEIE);//disable the DMA2D interrupt
 			//set occupied to free
-			display::set_frameBuff_state(false);
-			display::set_dma2d_state(false);
+			display::set_framebuffer_busy(false);
+			display::set_dma2d_busy(false);
 	
 	}
 	
@@ -56,9 +56,9 @@ void DMA2D_IRQHandler(void){
 namespace display {
 	void update_ltdc_for_mode();
 	
-  __IO uint32_t dma2d_stepCount = 0;
-  __IO bool frameBuffOccupied = false;
-  __IO bool dma2dOccupied = false;
+  __IO State state = DMA2D_FINISH;
+  __IO bool framebuffer_busy = false;
+  __IO bool dma2d_busy = false;
   
   // lo and hi res screen back buffers
   Surface __fb_hires((uint8_t *)&__fb_start, PixelFormat::RGB, Size(320, 240));
@@ -145,9 +145,9 @@ namespace display {
 		//enable the DMA2D interrupt
 		SET_BIT(DMA2D->CR, DMA2D_CR_TCIE|DMA2D_CR_TEIE|DMA2D_CR_CEIE);
 		//set DMA2d steps //set occupied
-    dma2d_stepCount = 0;
-    set_dma2d_state(true);
-    set_frameBuff_state(true);
+    state = DMA2D_FINISH;
+    set_dma2d_busy(true);
+    set_framebuffer_busy(true);
 		//MODIFY_REG(renderReg,DMA2DOccupiedState,DMA2DIsOccupied);
 		//MODIFY_REG(renderReg,FrameBuffOccupiedState,FrameBuffIsOccupied);
 		//MODIFY_REG(renderReg,DMA2DStepState,0<<DMA2DStepPos);
@@ -182,9 +182,9 @@ namespace display {
 		//MODIFY_REG(renderReg,DMA2DOccupiedState,DMA2DIsOccupied);
 		//MODIFY_REG(renderReg,FrameBuffOccupiedState,FrameBuffIsOccupied);
 		//MODIFY_REG(renderReg,DMA2DStepState,0<<DMA2DStepPos);
-    dma2d_stepCount = 0;
-    set_dma2d_state(true);
-    set_frameBuff_state(true);
+    state = DMA2D_FINISH;
+    set_dma2d_busy(true);
+    set_framebuffer_busy(true);
     // trigger start of dma2d transfer
     DMA2D->CR |= DMA2D_CR_START;
     // update pal next, dma2d could work at same time
@@ -221,9 +221,9 @@ namespace display {
     DMA2D->OOR = 1;
 		SET_BIT(DMA2D->CR, DMA2D_CR_TCIE|DMA2D_CR_TEIE|DMA2D_CR_CEIE);//enable the DMA2D interrupt
 		//set DMA2d steps //set occupied
-    dma2d_stepCount = 3;
-    set_dma2d_state(true);
-    set_frameBuff_state(true);
+    state = DMA2D_LORES_STEP_2;
+    set_dma2d_busy(true);
+    set_framebuffer_busy(true);
 		//MODIFY_REG(renderReg,DMA2DOccupiedState,DMA2DIsOccupied);
 		//MODIFY_REG(renderReg,FrameBuffOccupiedState,FrameBuffIsOccupied);
 		//MODIFY_REG(renderReg,DMA2DStepState,3<<DMA2DStepPos);
@@ -233,7 +233,7 @@ namespace display {
   }
 	
 	
-	void dma2d_lores_flip_Step2(void){
+	void dma2d_lores_flip_step2(void){
 		//Step 2.  
 			// set the transform type (clear bits 17..16 of control register)
 		MODIFY_REG(DMA2D->CR, DMA2D_CR_MODE, LL_DMA2D_MODE_M2M);
@@ -252,14 +252,14 @@ namespace display {
 			// set the output offset
 		DMA2D->OOR = 1;
 				// trigger start of dma2d transfer
-		dma2d_stepCount = 2;
+		state = DMA2D_LORES_STEP_3;
 		DMA2D->CR |= DMA2D_CR_START;
 	}
 
 
 
 
-	void dma2d_lores_flip_Step3(void){
+	void dma2d_lores_flip_step3(void){
 		//step 3.
 		// set the transform type (clear bits 17..16 of control register)
     MODIFY_REG(DMA2D->CR, DMA2D_CR_MODE, LL_DMA2D_MODE_M2M);
@@ -277,13 +277,13 @@ namespace display {
     DMA2D->FGOR = 0;
     // set the output offset
     DMA2D->OOR = 160;
-		dma2d_stepCount = 1;
+		state = DMA2D_LORES_STEP_4;
 			// trigger start of dma2d transfer
 		DMA2D->CR |= DMA2D_CR_START;
 
 	}
 
-	void dma2d_lores_flip_Step4(void){
+	void dma2d_lores_flip_step4(void){
 		// set the transform type (clear bits 17..16 of control register)
     MODIFY_REG(DMA2D->CR, DMA2D_CR_MODE, LL_DMA2D_MODE_M2M);
     // set source pixel format (clear bits 3..0 of foreground format register)
@@ -300,7 +300,7 @@ namespace display {
     DMA2D->FGOR = 160;
     // set the output offset
     DMA2D->OOR = 160;
-		dma2d_stepCount = 0;
+    state = DMA2D_FINISH;
 			// trigger start of dma2d transfer
 		DMA2D->CR |= DMA2D_CR_START;
 
@@ -389,23 +389,23 @@ namespace display {
   }
 	
 	
-	bool is_frameBuff_occupied(void){
-    return frameBuffOccupied;
+	bool is_framebuffer_busy(void){
+    return framebuffer_busy;
 	}
 	
-	void set_frameBuff_state(bool occupied){
-		frameBuffOccupied = occupied;
+	void set_framebuffer_busy(bool busy){
+		framebuffer_busy = busy;
 	}
 	
-	bool is_dma2d_occupied(void){
-		return dma2dOccupied;
+	bool is_dma2d_busy(void){
+		return dma2d_busy;
 	}
 	
-	void set_dma2d_state(bool occupied){
-		dma2dOccupied = occupied;
+	void set_dma2d_busy(bool busy){
+		dma2d_busy = busy;
 	}
 	
-	uint32_t get_dma2d_count(void){
-		return dma2d_stepCount;
+	State get_dma2d_state(void){
+		return state;
 	}
 }

```

**Comment by Gadgetoid** [comment]
Did you want to rebase out those pull-request merges, or should I just squash-n-merge?

**Comment by zenodante** [comment]
> Did you want to rebase out those pull-request merges, or should I just squash-n-merge?

Squash-n-merge would be fine! Thanks! And don't forget with your #510 ltdc fix together;)

**Pull request merged**
