### PR TITLE
All types changed to CamelCase. Examples fixed.

### PR DESCRIPTION
**Pull request by lowfatcode**
Sorry Phil.

### CODE REVIEW

**Comment by Daft-Freak** [comment]
Hopefully the conflicts from us both fixing the same thing aren't so bad...

**Comment by Gadgetoid** [comment]
Oof from the latest failure it looks like `serial-debug/serial-debug.cpp` isn't in the VS project. Adding this as a reminder to myself to add it!

**Comment by Gadgetoid** [comment]
Same issue again with `text.cpp`. Right now the Visual Studio solution is building, but `text.cpp` is not.

**Comment by Daft-Freak** [comment]
I think I wrote that example before the VS solution was merged.

**Comment by Gadgetoid** [comment]
It's a shame Visual Studio needs a project file for every example- hard to catch if you're on another platform (usually Code and WSL in my case). There's probably some linting we can use to catch that, so we keep on top of maintaining them. Having the VS project is super handy for debugging/cleaning up errors/warnings.

**Pull request merged**
