### PR TITLE
WIP: Add a version field to the API section

### PR DESCRIPTION
**Pull request by Daft-Freak**
Break everything. Needs some checking somewhere.

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Yeah I can't quite envision *how* this should be checked.

I guess it would have to be load-time- since it would have to trap:
1. Games being loaded from ext flash that are incompatible with a newly updated firmware
2. Games being loaded from SD that are incompatible

I think if we append-only the API we can gently skirt around issues and avoid needing to to this.

**Comment by Daft-Freak** [comment]
I was thinking maybe an init check somewhere for the version being too low. Still only handles append-only, but at least a game can abort early instead of randomly crashing later. Could even be a major/minor thing and abort on major mismatch...

(Sorry, intended to expand the description.)

**Comment by Daft-Freak** [comment]
So, that approach was okay then? (Forgot again to comment after updating...)

**Comment by Gadgetoid** [comment]
It seems sensible enough- we can expand it by barfing up a human-readable error but that's not super important.

I did wonder about something like `errno` so launching a game can fail in one of many ways which can then be communicated...  but then I couldn't think of any other error cases that shouldn't just be handled by the game itself (missing assets for example)

**Pull request merged**
