### PR TITLE
Added Waveform Demo using 32Blit Audio API

### PR DESCRIPTION
**Pull request by ThePythonator**
Created basic demo which generates 8 different sound effects when the corresponding button is pressed (d-pad and ABXY).

If the comments are insufficient please let me know.

Two of the sound effects sound rather similar but I couldn't come up with another one, suggestions are appreciated.

### CODE REVIEW

**Comment by Daft-Freak** [comment]
Secret other example list: https://github.com/pimoroni/32blit-beta/blob/master/site/examples/index.html#L46

**Comment by ThePythonator** [comment]
Thanks @Daft-Freak , didn't spot that 😀

**Comment by ThePythonator** [comment]
If there's anything else, please let me know, although I'll also have a quick search through...

**Comment by Gadgetoid** [comment]
I just spent far too long playing with this. Love it.

:laughing:

**Pull request merged**
