### PR TITLE
Some firmware refactoring

### PR DESCRIPTION
**Pull request by Daft-Freak**
An attempt to de-duplicate and reorganise the flashing code in the firmware. There are a lot of things this could potentially break...

I've tested (at least I think):

SD flash installed
SD flash not installed
SD flash different version

CDC flash not installed
CDC flash installed
CDC flash different version
CDC flash launcher

CDC save

firmware update from SD
launcher update from SD

### CODE REVIEW

**Comment by Gadgetoid** [comment]
I think the other thing I'd change is making the category for "Firmware Updater" just "firmware" and scanning for that instead of the title. Probably more for consistency, but I guess it also permits a rename (appending version number?) and saves uh... a whopping 8 bytes?

**Comment by Gadgetoid** [comment]
Okay really weird edge case here:

1. hex edit `launcher.blit` and change the version, I used `v1.0.1`
2. flash is to *SD card*
3. Check "root" and observe that the Launcher version v1.0.1 is present
4. reset
5. `launcher.blit` is deleted from the SD card, but *not* installed

I guess it should either
a. not delete `launcher.blit` at all it hasn't installed or
or
b. install it if it's newer, but then still a?

**Comment by Daft-Freak** [comment]
I think that's because the CRC is the same, so it assumes it's already installed (version field is pretty much ignored). If it doesn't delete the launcher you could end up with it doing an auto-downgrade if you later installed a newer launcher through another method...

**Comment by Gadgetoid** [comment]
Aaaah! That makes sense.

**Comment by Gadgetoid** [comment]
You're right- leaving `launcher.blit` hanging around is probably a bad idea- if I delete the running launcher it will immediately install from that file, and who knows what might be there :laughing:

**Comment by Gadgetoid** [comment]
This passed any test I could contrive for it, thank you! I hope this will pay off in future when someone has an idea for the firmware and no longer runs screaming from our finest organically grown code :laughing:

**Pull request merged**
