### PR TITLE
Generate version number defines

### PR DESCRIPTION
**Pull request by Daft-Freak**
A bit of a WIP as I'm not sure where the defines/header should go (probably somewhere internal). Also, left a test commit in, and VS is broken. Inspired by #216. 

Test release here: https://github.com/Daft-Freak/32blit-beta/releases/tag/1.2.3

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Ah, of course. Helpful Visual Studio does not invoke CMake to generate the version number include.

**Comment by Daft-Freak** [comment]
I'll probably just add a placeholder file for the VS solution since it isn't used to build releases.

**Comment by Daft-Freak** [comment]
Builds everywhere now. Changed to a pair of getters to avoid include path fun.

**Comment by Gadgetoid** [comment]
This looks entirely sensible! Thank you.

**Comment by Daft-Freak** [comment]
Oh, I left the test commit in! :man_facepalming:

**Pull request merged**
