### PR TITLE
Don't include the firmware in every app

### PR DESCRIPTION
**Pull request by Daft-Freak**
Part two of the quest for PIC (#220)...

This probably needs a lot of testing. Known issues:
 - ~If you don't call `set_screen_mode` in `init`, you don't get a screen.~
 - ~"Exit Game" is mostly broken (it does return to the file list, but with whatever screen mode the app set and the app's sound still going)~
 - The memory allocations might need adjusting (user code is similar to before, firmware heap/bss is in RAM_D2)
 - ~Timers are broken~

### CODE REVIEW

**Comment by Daft-Freak** [comment]
https://github.com/pimoroni/32blit-beta/pull/269/commits/7ca49a3263747b454fdee6c10e9a3526903ad76a / https://github.com/pimoroni/32blit-beta/pull/269/commits/04b0e7321352c4ac332878b04fe818de54841cb2 get timers working, but seem a bit messy...

**Comment by Daft-Freak** [comment]
Default screen mode is back, exit works and the examples seem to work.

**Comment by Daft-Freak** [comment]
The Windows builds failed... because Travis didn't run them on Windows? :confused:

**Comment by zenodante** [comment]
> Part two of the quest for PIC...
> 
> This probably needs a lot of testing. Known issues:
> 
> * ~If you don't call `set_screen_mode` in `init`, you don't get a screen.~
> * ~"Exit Game" is mostly broken (it does return to the file list, but with whatever screen mode the app set and the app's sound still going)~
> * The memory allocations might need adjusting (user code is similar to before, firmware heap/bss is in ITCMRAM)
> * ~Timers are broken~

Put heap/bss in ITCMRAM may not a right place. It's only for fast code in ram and ARM don't suggested you to put other stuff into it.

**Comment by Daft-Freak** [comment]
Hmm, that makes sense. I think that part came from @Gadgetoid's original patch.

**Comment by Daft-Freak** [comment]
Just fixed the "currently running from" and reset commands so that the tool doesn't attempt to write ext flahs while running from it... Interestingly, saving bins to SD worked in the background.

**Comment by Daft-Freak** [comment]
(A few more rebases later...)

So, this is at the point where everything seems to work (I've been running it for a while now). Not sure if there's anything left that needs tidying up?

**Comment by Gadgetoid** [comment]
We've got a tag and release for a previous stable build, so we should be able to merge this and go onwards and upwards!

**Comment by Gadgetoid** [comment]
A momentus occasion!

Thanks for all your work on this monster of a change, it's a heck of an improvement in more ways than I could list.

**Pull request merged**
