### PR TITLE
Unshorten CMake instructions

### PR DESCRIPTION
**Pull request by Daft-Freak**
-B isn't supported until CMake 3.13, which is newer than the version in Ubuntu 18.04 which is used in WSL. :cry:

### CODE REVIEW

**Comment by Gadgetoid** [comment]
D'oh!

I believe the `emcmake` command is still valid as a short-hand for including the full path to the toolchain file. I used it in WSL recently and it worked for me.

**Comment by Daft-Freak** [comment]
Ah, yes that can stay.

**Comment by Daft-Freak** [comment]
There, it's now a "mostly revert"

**Comment by Gadgetoid** [comment]
Brilliant! Thank you.

**Pull request merged**
