### PR TITLE
Giant pile of tidying

### PR DESCRIPTION
**Pull request by Daft-Freak**
Went to adjust a few things, got carried away... Some of this is more clang-tidy warnings. (Interestingly it can detect more double-promotions than GCC can.)

### CODE REVIEW

**Comment by AndrewCapon** [comment]
Remove redundant voids!

Madness :)

**Comment by Gadgetoid** [comment]
Is there any way we can run clang tidy with a `--check-only` flag in Travis to prevent any new issues from creeping in?

**Comment by Gadgetoid** [comment]
Thank you- had a quick skim and it all looks completely rational. We could definitely use some gentle code style nudges, but don't want to put up too many barriers to entry.

**Comment by AndrewCapon** [comment]
What we need is ```-outmoded-old-buggers``` for my code.

**Pull request merged**
